version: '3.8'

services:
  denis-app:
    image: quarkus/apsidart-backend-jvm:latest
    build: 
      context: .
    container_name: denis-app
    ports:
      - "8080:8080"
    depends_on:
      - denis-db
    environment:
      - QUARKUS_DATASOURCE_DB_KIND=postgresql
      - QUARKUS_DATASOURCE_USERNAME=denis
      - QUARKUS_DATASOURCE_PASSWORD=admin
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://denis-db:5432/denis_db
      - QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION=update

  denis-db:
    image: postgres:15
    restart: always
    container_name: denis-db
    environment:
      POSTGRES_USER: denis
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: denis_db
    ports:
      - "5432:5432"
    volumes:
      - postgresv15:/var/lib/postgresql/data

volumes:
  postgresv15:
    driver: local
